production.h File Reference
Functions
bool production (int argc, char *argv[])
int calculate_days_in_month (int year, int month)
int is_leap_year (int year)
int calculate_day_of_week (int day, int month, int year)
int is_valid_month (int month)
int is_valid_day (int year, int month, int day)
Function Documentation
calculate_day_of_week()
int calculate_day_of_week (int day, int month, int year)
Determines what day of the week a particular date falls on.
Parameters
day Day of the month, counting from 1.
month Range 0 through 11, where January = 0.
year The year.
Returns
-1 for invalid input (e.g., year < 1752, month out of range, day < 1 or > appropriate for that month & year 0 through 6, where Sunday = 0.
References is_valid_day(), and is_valid_month().
Referenced by production(), and testCalcDayOfWeek().
calculate_days_in_month()
int calculate_days_in_month (int year, int month)
Calculates how many days are in a given month for a given year.
Parameters
year The year we are checking.
month The month we are checking. Range 0 through 11, where January = 0.
Returns
Days of the month in that specific year -1 if invalid input (e.g., year < 1752, month out of range).
References is_leap_year(), and is_valid_month().
Referenced by production(), and testCalcDaysInMonth().
is_leap_year()
int is_leap_year (int year)
Test if a given year is a leap year or not.
Parameters
year The year we are testing
Returns
1 if it is a valid leap year. 0 if a valid year, but not a leap year. -1 if not a valid year (i.e. before the calendar rule changed in 1752).
Referenced by calculate_days_in_month(), is_valid_day(), and testIsLeapYear().
is_valid_day()
int is_valid_day (int year, int month, int day)
Function to tell whether a day is valid or not
Given a month, day, and year, the function checks to see if it is possible for that day to occur in the year and month specified
Parameters
year the year
month the month
day the day
Returns
-1 if invalid day, 1 if valid.
References is_leap_year().
Referenced by calculate_day_of_week().
is_valid_month()
int is_valid_month (int month)
Function to tell whether a month is valid or not
Given a month, it determines if it is between 0 and 11 inclusive.
Parameters
month the month
Returns
-1 if not valid, 1 if valid.
Referenced by calculate_day_of_week(), and calculate_days_in_month().
production()
bool production (int argc, char * argv[])
Specify the year either as the first program argument, or pass in an argument at run-time and it will print a calendar from January to December.
Parameters
argc Number of words on the command line
argv Array of pointers to character strings representing the words on the command line.
Returns
true if Program was able to print a calendar. false if User entered bad input.
References calculate_day_of_week(), and calculate_days_in_month().
Referenced by main().