tests.c File Reference
#include <stdbool.h>
#include `tests.h`
#include `production.h`
#include <stdio.h>
#include <stdlib.h>
Functions
bool tests (void)
bool testIsLeapYear (void)
bool testCalcDaysInMonth (void)
bool testCalcDayOfWeek (void)
Function Documentation
testCalcDayOfWeek()
bool testCalcDayOfWeek (void)
References calculate_day_of_week().
Referenced by tests().
testCalcDaysInMonth()
bool testCalcDaysInMonth (void)
References calculate_days_in_month().
Referenced by tests().
testIsLeapYear()
bool testIsLeapYear (void)
Tests whether the leap year function works.
Parameters
year Year we are testing
Returns
true if all test case pass. False otherwise.
References is_leap_year().
Referenced by tests().
tests()
bool tests (void)
Function to perform tests.
Returns
true if all tests succeed, false if even one fails
References testCalcDayOfWeek(), testCalcDaysInMonth(), and testIsLeapYear().
Referenced by main().